### ISSUE TITLE
Confusion on control mode

### ISSUE THREAD

**Issue by changhaonan** [PKU-MARL/DexterousHands#15]
Hi, 
I am currently reading your implementation of shadow_hand_push_block.py.
I am kind of confused about the control mode of the control mode. In line 299, you write: `asset_options.default_dof_drive_mode = gymapi.DOF_MODE_NONE`. But in pre_physics_step, in line 1169, you are using `self.gym.set_dof_position_target_tensor_indexed`, which infers that you are using POS control.  I read for multiple times, still very confused about where did you set the control mode to POS control??

**Comment by cypypccpy** [comment]
hi @changhaonan,

```
But in pre_physics_step, in line 1169, you are using self.gym.set_dof_position_target_tensor_indexed, which infers that you are using POS control
```

Yeah we are using the POS control.

```
I read for multiple times, still very confused about where did you set the control mode to POS control??
```

In fact, the DOF mode is set in the MJCF file and loaded by Isaac Gym:
![image](https://user-images.githubusercontent.com/55881363/205418606-c0513c20-9731-4dd1-9e36-a51121096196.png)

So this overrides the previous `DOF_MODE_NONE`. I'm sorry for confusing you and will add a comment here later.

Hope this can help you.

**Comment by changhaonan** [comment]
OK. Thanks. That explains.
