### ISSUE TITLE
Potential collision mesh errors in some tasks

### ISSUE THREAD

**Issue by wkwan7** [PKU-MARL/DexterousHands#2]
Thanks for your great work!
I tested some tasks and found that there seemed to be some mistakes in some environment like **ShadowHandGraspAndPlace**. According to the collision mesh of the bucket in the environment below, the opening of the bucket is closed and objects cannot be put in. Is this a bug? I think it might be necessary to do convex decomposition on the bucket.
![image](https://user-images.githubusercontent.com/55489322/172340379-058c8356-1924-4550-8c43-6e130bbafccb.png)

**Comment by cypypccpy** [comment]
Thanks! Yeah you are right, a convex decomposition is forgot to do here, you can add the following code under the object_asset_option, using the convex decomposition method that comes with isaacgym, just like we did in the door environment:
```        
object_asset_options = gymapi.AssetOptions()  
object_asset_options.density = 500  
object_asset_options.fix_base_link = True  
object_asset_options.disable_gravity = True  
object_asset_options.use_mesh_materials = True  
object_asset_options.mesh_normal_mode = gymapi.COMPUTE_PER_VERTEX 
object_asset_options.override_com = True 
object_asset_options.override_inertia = True 
object_asset_options.vhacd_enabled = True 
object_asset_options.vhacd_params = gymapi.VhacdParams() 
object_asset_options.vhacd_params.resolution = 200000 
object_asset_options.default_dof_drive_mode = gymapi.DOF_MODE_NONE
```
This part of the environment is still under development, we will release all env and algorithms in the new version, as well as fix some such bugs. The time will be about mid-June :)

**Comment by wkwan7** [comment]
Thanks!
