### ISSUE TITLE
Issues about visual observation

### ISSUE THREAD

**Issue by jiangranlv** [PKU-MARL/DexterousHands#20]
hi, yuanpei @cypypccpy. Nice work again!
It seems like something is wrong when I try to use point cloud observation in the task.
Specifically, using the camera through isaacgym API may have some bugs. I print the 'camera_handle', whose value is -1.
![图片](https://user-images.githubusercontent.com/66426987/222346503-172282cb-dc33-4887-83a0-f609fd6186f8.png)
![图片](https://user-images.githubusercontent.com/66426987/222347095-37cd635b-5611-4e53-b4c8-e0649b0cb9ff.png)

Could you please help me? Thanks a lot~

**Comment by cypypccpy** [comment]
Hi @jiangranlv ,

Thanks. I just tried it and it should work fine:
```
python train.py --task ShadowHandOver --algo ppo
``` 
![image](https://user-images.githubusercontent.com/55881363/222347381-cb6e71d9-ec00-45ad-846c-1920463f3702.png)

Errors that return -1 generally appear when using isaacgym on servers without a monitor, are you in this case? And using --headless may also cause this bug. Currently, isaacgym has many bugs with rendering, maybe you can also go to the isaacgym official [forum](https://forums.developer.nvidia.com/c/agx-autonomous-machines/isaac/isaac-gym/322) to find some answers.

Hope this can help you.

**Comment by jiangranlv** [comment]
> 

I did use isaacgym on servers without a monitor, and using the headless mode. Thank you very much.

**Comment by TengBoYuu** [comment]
> > 
> 
> I did use isaacgym on servers without a monitor, and using the headless mode. Thank you very much.

Hi, I have the same problem, how did you fix it. Thx☺️
